Version2
wecode-bootcamp-korea/37-backend-westagram pull request #13
Opened 2022-08-31 06:29 UTC by dyjeong576

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-31 08:48 UTC, lordmyshepherd requested changes

2022-08-31 08:48 UTC, lordmyshepherd commented on teamC/JeongDayoung/.gitignore
> +.env
👍🏻

2022-08-31 08:48 UTC, lordmyshepherd commented on teamC/JeongDayoung/.env.sample
> +TYPEORM_LOGGING  true;
```suggestion
TYPEORM_LOGGING  true
```

2022-08-31 08:48 UTC, lordmyshepherd commented on teamC/JeongDayoung/.env.sample
> +database_url = url;
데이터베이스 URL이 두 개네요?

무슨 차이가 있나요?

```suggestion
DATABASE_URL = "mysql://user:password@127.0.0.1:3306/westagram2"

database_url = url;
```

2022-08-31 08:48 UTC, lordmyshepherd commented on teamC/JeongDayoung/app.js
> +const myDataSource = new DataSource({
- myDataSource 보다는 `appDataSource` , `mysqlDataSource` 혹은 간결하게 `database`로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.
- DataSource.initialize() 함수가 실행되고 나면, then()과 catch()를 사용해서 에러를 핸들링해줄 수 있습니다. 이렇게 하면, initialize() 함수가 실행되어서 database와 실제로 connection을 생성할 때, 성공했는지 실패했는지 여부를 확인할 수 있습니다.
- 추후 에러 핸들링을 담을 때의 가독성 및 확장성 보장을 위해 ".then"을 (typeorm datasource 공식문서에서 제안하는 것 처럼) 한칸 아래로 띄는 것을 권장드립니다.
- 참고 링크: [https://typeorm.biunav.com/en/data-source.html#what-is-datasource](https://typeorm.biunav.com/en/data-source.html#what-is-datasource)

2022-08-31 08:48 UTC, lordmyshepherd commented on teamC/JeongDayoung/app.js
> +  });
아래와 같이 then()에 catch()를 체이닝해서 데이터베이스와 컨넥션을 생성하는 과정에서 실패하는 경우 error를 출력하도록 만들어주세요-! 🙇🏻 

```javascript
    .catch((err) => {
        console.error("Error during Data Source initialization", err)
    })
```

2022-08-31 08:48 UTC, lordmyshepherd commented on teamC/JeongDayoung/app.js
> +})
arrow function을 사용해서 한 줄로 수정해주세요~
```suggestion
app.get('/ping', (req, res, next) => res.json({message : 'pong'})
```

2022-08-31 08:48 UTC, lordmyshepherd commented on teamC/JeongDayoung/app.js
> +})
추가로 `cors()`는 line 13에 `app.use(cors())`로 선언해서 모든 엔드포인트 (/ping, /users 등)에 적용될 수 있도록 만들어주세요.

2022-08-31 08:48 UTC, lordmyshepherd commented on teamC/JeongDayoung/app.js
> +})
- SQL 문법도 가독성 좋게 만들어주는 것이 중요합니다. 회사마다 컨벤션이 다르겠지만, 위코드에서는 아래와 같은 SQL 문법의 컨벤션을 정하고 있습니다.
- 지금은 위코드에서 사용하고 있는 컨벤션을 지켜서 문법을 작성해주세요. 하지만 이는 회사마다 다르기 때문에, 정답이 아님을 반드시 인지해주세요.
- SQL 포맷팅은 다음 처럼 통일하면 좋을거 같습니다.
    
    ```jsx
    // Example
    await database.query(`
          INSERT INTO users (
              name,
              email,
              profile_image,
              password
          ) VALUES (?, ?, ?, ?)`,
          [ name, email, profile_image, password ]
    );
    
    ```

2022-08-31 08:48 UTC, lordmyshepherd commented on teamC/JeongDayoung/app.js
> +  await myDataSource.query(
line 36, 37 사이는 한 줄 띄워주세요~

2022-08-31 08:48 UTC, lordmyshepherd commented on teamC/JeongDayoung/package.json
> +    "mysql2": "^2.3.3",
mysql mysql2 둘 중에 하나만 남기고 지워주세요~

2022-08-31 08:48 UTC, lordmyshepherd commented on teamC/JeongDayoung/package.json
> +    "mysql2": "^2.3.3",
동일한 역할을 수행하는 라이브러리 입니다.

2022-09-01 04:11 UTC, dyjeong576 commented on teamC/JeongDayoung/.env.sample
> +database_url = url;
port를 잘못 적었습니다!

2022-09-01 06:42 UTC, closed without merging