[정다영-teamC] Assignment 2: Express API - 유저 회원가입 하기
wecode-bootcamp-korea/37-backend-westagram pull request #29
Opened 2022-09-01 08:22 UTC by dyjeong576

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 유저 회원가입하기 기능 구현
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-09-01 08:38 UTC, lordmyshepherd requested changes

2022-09-01 08:38 UTC, lordmyshepherd commented on teamC/dayoung/app.js
> +    await appDataSource.query(`INSERT INTO users(
line 37, 38 사이에 한 줄 띄워주세요~

2022-09-01 08:38 UTC, lordmyshepherd commented on teamC/dayoung/app.js
> +    const {name, email, profile_image, password} = req.body;
```suggestion
    const { name, email, profile_image, password } = req.body;
```

2022-09-01 08:38 UTC, lordmyshepherd commented on teamC/dayoung/app.js
> +    await appDataSource.query(`INSERT INTO users(
추가로 데이터베이스에 사용자를 등록하기 전에 email을 기준으로 중복 회원가입이 되지 않도록 추가 로직이 필요할 것 같습니다-!

2022-09-01 08:38 UTC, autoboy4commit commented on teamC/dayoung/app.js
> +    );
- SQL 문법도 가독성 좋게 만들어주는 것이 중요합니다. 회사마다 컨벤션이 다르겠지만, 위코드에서는 아래와 같은 SQL 문법의 컨벤션을 정하고 있습니다.
- 지금은 위코드에서 사용하고 있는 컨벤션을 지켜서 문법을 작성해주세요. 하지만 이는 회사마다 다르기 때문에, 정답이 아님을 반드시 인지해주세요.
- SQL 포맷팅은 다음 처럼 통일하면 좋을거 같습니다.
    
    ```jsx
    // Example
    await database.query(`
          INSERT INTO users (
              name,
              email,
              profile_image,
              password
          ) VALUES (?, ?, ?, ?)`,
          [ name, email, profile_image, password ]
    );
    
    ```

2022-09-02 03:31 UTC, lordmyshepherd requested changes

2022-09-02 03:31 UTC, lordmyshepherd commented on teamC/dayoung/app.js
> +  )
아래와 같은 방향으로 리펙토링 해보면 좋을 것 같습니다!
그리고 말씀하신 async는 vscode에서 자동완성 해주는 것 같아요! 

함수 안에서 await를 사용하려면, 반드시 함수를 async로 감싸주어야 하기 때문이에요!

```suggestion
  const { name, email, profile_image, password} = req.body;
  
  const user = await appDataSource.query(`
    SELECT
        id,
        name,
        email,
        profile_image AS profileImage,
        password
    FROM users
    WHERE email = "${email}"`
   )
  
   if () {res.status(200).json({"message" : "fail"});}

   await appDataSource.query(`INSERT INTO users(
          name, 
          email, 
          profile_image, 
          password
          )values(?, ?, ?, ?);`,
        [name, email, profile_image, password]
      );
  res.status(200).json({"message" : "userCreated"})
    }
  )
```

2022-09-02 03:55 UTC, dyjeong576 commented on teamC/dayoung/app.js
> +    await appDataSource.query(`INSERT INTO users(
수정했습니다!

2022-09-02 03:55 UTC, dyjeong576 commented on teamC/dayoung/app.js
> +    const {name, email, profile_image, password} = req.body;
수정했습니다!

2022-09-02 03:55 UTC, dyjeong576 commented on teamC/dayoung/app.js
> +    await appDataSource.query(`INSERT INTO users(
수정했습니다!

2022-09-02 17:05 UTC, dyjeong576 commented on teamC/dayoung/app.js
> +  )
수정했습니다!

2022-09-03 03:17 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-09-03 03:17 UTC, merged