[정다영-teamC] Assignment 3 : Express API - CRUD
wecode-bootcamp-korea/37-backend-westagram pull request #30
Opened 2022-09-01 08:31 UTC by dyjeong576

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 게시글 등록하기
- 전체 게시글 조회하기
- 유저의 게시글 조회하기
- 게시글 수정하기
- 게시글 삭제하기
- 좋아요 누르기
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-09-01 11:45 UTC, lordmyshepherd requested changes

2022-09-01 11:45 UTC, lordmyshepherd commented on teamC/dayoung/app.js
> +      }
- 작성하신 코드에서 DataSource.query()가 비동기적으로 실행되는 함수입니다.
- 비동기 처리를 하는 방법은 크게 callback, promise, async/await를 사용하는 방법이 있는데, 작성하신 코드에서는 이를 혼합해서 사용하고 있습니다. 아래 예제를 참고해서 리펙토링해주세요.
    
    ```jsx
    // callback 방식의 비동기처리
    app.get("/posts", (req, res) => {
        myDataSource.query(`SELECT * FROM users`,
          // 비동기 처리 이후에 실행되는 callback
          (err, data) => {res.status(200).json({ data: data })}
        );
    });
    
    // async와 await 방식의 비동기처리
    app.get("/posts", async(req, res) => {
      const users = await myDataSource.query(`SELECT * FROM users`);
      
      res.status(200).json({ data : users})
    });
    
    ```
    
- JavaScript에서 비동기 처리할 수 있는 callback과 async/await 방식의 차이를 알고 싶다면, 아래 영상(드림코딩 Youtbue)을 참고해주세요.
[https://www.youtube.com/watch?v=aoQSOZfz3vQ](https://www.youtube.com/watch?v=aoQSOZfz3vQ)

2022-09-01 11:45 UTC, lordmyshepherd commented on teamC/dayoung/app.js
> +  app.post("/likes/:user_id", async(req, res, next) => {
- 좋아요 기능을 구현할 때에는 주의해야할 점이 있습니다.
- 하나의 사용자가 하나의 게시물에 대해서 좋아요를 할 수 있는 횟수는 단 한 번 이어야 합니다.
- 지금 구조에서는 좋아요를 누를 때마다 아래와 같이 likes 테이블에 계속해서 중복으로 데이터가 저장됩니다.
    
    ```sql
    +----+---------+---------+---------------------+
    | id | user_id | post_id | created_at          |
    +----+---------+---------+---------------------+
    |  1 |       1 |       3 | 2022-07-16 14:18:26 |
    |  2 |       1 |       3 | 2022-07-16 14:18:26 |
    |  3 |       1 |       3 | 2022-07-16 14:18:26 |
    |  4 |       1 |       3 | 2022-07-16 14:18:26 |
    |  5 |       1 |       3 | 2022-07-16 14:18:47 |
    |  6 |       1 |       3 | 2022-07-16 14:18:47 |
    +----+---------+---------+---------------------+
    ```
    
- 이를 막기 위해서, likes 테이블에 user_id와 post_id를 기준으로 UNIQUE 제약조건을 추가하는 migration 파일을 추가로 만들어서 올려주세요.

2022-09-01 11:45 UTC, lordmyshepherd commented on teamC/dayoung/app.js
> +    const postId = req.params.post_id;
javascript에서는 snake_case가 아니라 camelCase를 사용해주세요~
```suggestion
    const postId = req.params.postId;
```

2022-09-01 11:45 UTC, lordmyshepherd commented on teamC/dayoung/app.js
> +    const postId = req.params.post_id;
javascript에서는 snake_case가 아니라 camelCase를 사용해주세요~
```suggestion
    const postId = req.params.postId;
```

2022-09-01 11:45 UTC, lordmyshepherd commented on teamC/dayoung/app.js
> +    const postId = req.params.post_id;
javascript에서는 snake_case가 아니라 camelCase를 사용해주세요~
```suggestion
    const postId = req.params.postId;
```

2022-09-01 11:45 UTC, lordmyshepherd commented on teamC/dayoung/app.js
> +      }
아래 모든 코드에 적용해 주세요~

2022-09-02 12:49 UTC, dyjeong576 commented on teamC/dayoung/app.js
> +    const postId = req.params.post_id;
수정했습니다!

2022-09-02 12:49 UTC, dyjeong576 commented on teamC/dayoung/app.js
> +    const postId = req.params.post_id;
수정했습니다!

2022-09-02 12:50 UTC, dyjeong576 commented on teamC/dayoung/app.js
> +    const postId = req.params.post_id;
수정했습니다!

2022-09-02 12:55 UTC, dyjeong576 commented on teamC/dayoung/app.js
> +  app.post("/likes/:user_id", async(req, res, next) => {
수정했습니다!

2022-09-02 13:35 UTC, dyjeong576 commented on teamC/dayoung/app.js
> +      }
수정했습니다!

2022-09-04 12:23 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-09-04 12:23 UTC, merged