[김응수-teamB] Assignment 1 | Project Layered pattern 적용
wecode-bootcamp-korea/37-backend-westagram pull request #60
Opened 2022-09-06 03:59 UTC by eungsooKIM

## 수정 사항 간략한 한줄 요약
        app.js의 기능을 routes/controllers/services/models 로 분화
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
        routes : endpoint를 분리해서 해당 endpoint에 집중. endpoint와 controller를 연결.
        controllers : request와 response에 대한 처리만을 담당. service layer를 호출하고, response를 반환.
        services : 필요한 비즈니스 로직을 담당한 후, model layer를 호출하고, controller layer로 결과를 반환.
        models : 데이터베이스와의 통신만을 담당한 후, service layer로 결과를 반환.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
해당코드의 POST /posts엔드포인트로 작성한  글은 DELETE /posts로 삭제할 수 있으나
mysql에서 INSERT 명령으로 직접 작성한 글은 해당 코드의 DELETE/posts로 삭제할 수 없다고 뜨는데 해결방법이 있는지 궁금합니다!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-09-07 03:07 UTC, Kang-kyunghun requested changes

2022-09-07 03:07 UTC, Kang-kyunghun commented on teamB/eungSooKim/controllers/postControllers.js
> +      return res.status(400).json({ message: "제목과 내용을 입력하세요" });
되도록 메시지는 영어로 적어주세요.

2022-09-07 03:07 UTC, Kang-kyunghun commented on teamB/eungSooKim/controllers/postControllers.js
> +      message: "게시되었습니다",
여기도 메시지 영어로 수정해 주세요.

2022-09-07 03:07 UTC, Kang-kyunghun commented on teamB/eungSooKim/controllers/postControllers.js
> +const postsList = async (req, res) => {
함수 이름을 지을 때 동상형을 시작하여 어떤 행위를 하는지 나타내는 것이 좋습니다.
다른 부분들은 잘 적용하셨습니다. 
```suggestion
const getPostsList = async (req, res) => {
```

2022-09-07 03:07 UTC, Kang-kyunghun commented on teamB/eungSooKim/controllers/postControllers.js
> +const delPost = async (req, res) => {
```suggestion
const deletePost = async (req, res) => {
```

2022-09-07 03:07 UTC, Kang-kyunghun commented on teamB/eungSooKim/controllers/userControllers.js
> +      return res.status(400).json({ message: "유저id를입력하세요" });
메시지 확인해 주세요.

2022-09-07 03:07 UTC, Kang-kyunghun commented on teamB/eungSooKim/models/likeDao.js
> +    error.statusCode = 500;
개발자가 에러헨들링 한 에러의 경우 4xx번대 상태코드를 사용해 주세요.

일반적으론 500은 개발자가 헨들링하지 못한 에러가 발생했을 때 나오는 코드 입니다.

2022-09-07 03:07 UTC, Kang-kyunghun commented on teamB/eungSooKim/models/postDao.js
> +const postsList = async () => {
```suggestion
const getPostsList = async () => {
```

2022-09-07 03:07 UTC, Kang-kyunghun commented on teamB/eungSooKim/models/userDao.js
> +const userPosts = async (userId) => {
user 정보와 해당 user가 작성한 게시글을 가져오는 역할로 보이는데,
dao에서 이렇게 sql을 만들지 말고, 서비스에서 user정보를 가져오는 dao 한 번 호출, 특정 user가 작성한 게시물 목록 가져오는 dao한 번 호출, 총 2번의 dao를 호출하는 식으로 구성하면 더 좋을 것 같습니다.

2022-09-07 03:07 UTC, Kang-kyunghun commented on teamB/eungSooKim/routers/index.js
> +router.use("/likes", likeRouter.router);
코드 자체에는 이상이 없지만, 가독성 및 컨벤션을 위해 다음과 같이 수정하면 좋을 것 같습니다.

1. require은 결국 다른 곳에 짜여진 코드를 불러 오는 것입니다. 그래서 require은 상단에 다 모아 둡니다.
2. 모아 둘 때도 3가지 그룹으로 나눠서 불러오는 일종의 약속 같은 것이 있습니다.
- 첫번째 그룹: node에서 기본적으로 제공하는 모듈
- 두번째 그룹: npm install로 설치한 3rd-part 모듈
- 세번째 그룹: 프로젝트 내에서 작성한 모듈 


```suggestion
const express = require("express");

const userRouter = require("./userRouter");
const postRouter = require("./postRouter");
const likeRouter = require("./likeRouter");

const router = express.Router();

router.use("/users", userRouter.router);
router.use("/posts", postRouter.router);
router.use("/likes", likeRouter.router);
```

2022-09-07 03:07 UTC, Kang-kyunghun commented on teamB/eungSooKim/services/userService.js
> +    throw err;
1. 에러 메시지는 영어로 작성해 주시고, 디테일한 내용 보다는 간결하게 어떤 에러인지 파악할 수 있으면 됩니다. 해당 메시지는 사용자가 보는 것이 아닌, 프론트엔드에서 받아가는 메시지 입니다.
2. 상태코드 409는 PUT method 사용시 데이터 충돌 날 때 주로 쓰는 코드 입니다.
```suggestion
  if (!pwValidation.test(password)) {
    const err = new Error(
      "INVALID PASSWORD"
    );
    err.statusCode = 400;
    throw err;
```

2022-09-07 04:45 UTC, eungsooKIM commented on teamB/eungSooKim/models/userDao.js
> +const userPosts = async (userId) => {
경훈님 리뷰 감사합니다. 다른 리뷰사항은 모두 수정해서 새로 커밋했는데 이 부분에서 서비스에서 2번의 dao를 호출하는 방식으로 과제에서 요구하는 (https://study.wecode.co.kr/session/assignment/79)  형태의 배열출력을 만들수가없어서 해당 부분은 따로 질문드린뒤 다시 커밋하도록하겠습니다.

2022-09-08 00:35 UTC, eungsooKIM commented on teamB/eungSooKim/controllers/postControllers.js
> +      return res.status(400).json({ message: "제목과 내용을 입력하세요" });
수정완료했습니다

2022-09-08 02:48 UTC, Kang-kyunghun commented
LGTM

2022-09-08 02:48 UTC, merged