[정다영-teamC] Assignment 1 : Project Layered pattern 적용
wecode-bootcamp-korea/37-backend-westagram pull request #66
Opened 2022-09-06 08:43 UTC by dyjeong576

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- layered pattern 적용
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항
- req, res의 동작 원리를 모르겠습니다..
- await, async의 동작 원리를 모르겠습니다..

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-09-07 04:44 UTC, Kang-kyunghun requested changes

2022-09-07 04:44 UTC, Kang-kyunghun commented on teamC/dayoung/controllers/postController.js
> +const postInput = async (req, res) => {
함수 이름을 지을 때 행위+대상으로 지어주시면 좋습니다.
```suggestion
const createPost = async (req, res) => {
```

2022-09-07 04:44 UTC, Kang-kyunghun commented on teamC/dayoung/controllers/postController.js
> +const postCheck = async (req, res) => {
```suggestion
const getPostList = async (req, res) => {
```

2022-09-07 04:44 UTC, Kang-kyunghun commented on teamC/dayoung/services/userService.js
> +      err.statusCode = 409;
상태코드 409는 PUT method를 사용할 때 데이터와 충돌 할 경우 주로 사용됩니다.
front에서 잘 못된 입력 값을 준 것이므로 400으로도 충분할 것 같습니다.
```suggestion
      err.statusCode = 400;
```

2022-09-07 04:44 UTC, Kang-kyunghun commented on teamC/dayoung/models/postDao.js
> +const { DataSource } = require('typeorm');
- 전반적으로 들여씌기 한 번 확인해 주세요. 자바스크립트는 기본 들여씌기는 2칸입니다. 

- SQL 문법도 가독성 좋게 만들어주는 것이 중요합니다. 회사마다 컨벤션이 다르겠지만, 위코드에서는 아래와 같은 SQL 문법의 컨벤션을 정하고 있습니다.
- 지금은 위코드에서 사용하고 있는 컨벤션을 지켜서 문법을 작성해주세요. 하지만 이는 회사마다 다르기 때문에, 정답이 아님을 반드시 인지해주세요.
- SQL 포맷팅은 다음 처럼 통일하면 좋을거 같습니다.
```node
// Example
await database.query(`
      INSERT INTO users (
          name,
          email,
          profile_image,
          password
      ) VALUES (?, ?, ?, ?)`,
      [ name, email, profile_image, password ]
);
```

2022-09-07 04:44 UTC, Kang-kyunghun commented on teamC/dayoung/models/postDao.js
> +const DataPost = async ( postId) => {
전체적으로 함수 이름들 한 번씩 확인해 주세요.
```suggestion
const getPostList = async ( postId) => {
```

2022-09-07 05:29 UTC, dyjeong576 commented on teamC/dayoung/controllers/postController.js
> +const postInput = async (req, res) => {
수정했습니다.

2022-09-07 05:31 UTC, dyjeong576 commented on teamC/dayoung/controllers/postController.js
> +const postCheck = async (req, res) => {
수정했습니다.

2022-09-07 05:31 UTC, dyjeong576 commented on teamC/dayoung/services/userService.js
> +      err.statusCode = 409;
수정했습니다.

2022-09-07 05:33 UTC, dyjeong576 commented on teamC/dayoung/models/postDao.js
> +const { DataSource } = require('typeorm');
어느 부분을 수정해야 할지 모르겠습니다..ㅠㅠ

2022-09-07 05:46 UTC, dyjeong576 commented on teamC/dayoung/models/postDao.js
> +const DataPost = async ( postId) => {
수정했습니다.

2022-09-07 09:15 UTC, lordmyshepherd requested changes

2022-09-07 09:15 UTC, lordmyshepherd commented on teamC/dayoung/models/userDao.js
> +  });
모든 *Dao.js에서 지금 데이터베이스 인스턴스를 각각 만들어서 사용하고 있습니다.
이를 dataSource.js 파일로 옮기고, 필요한 파일에서 import 해서 사용하는 방향을 수정하면 좋을 것 같습니다.

dataSource를 여러번 만들어서 사용하면, 각각 데이터베이스와 컨넥션을 만들기 때문에 좋은 방향이 아니라고 생각해주시면 좋을 것 같습니다!

2022-09-07 09:15 UTC, lordmyshepherd commented on teamC/dayoung/models/userDao.js
> +    console.log(name, email, password, profileImage)
console.log()는 지워주세요~

```suggestion
```

2022-09-07 11:38 UTC, dyjeong576 commented on teamC/dayoung/models/userDao.js
> +    console.log(name, email, password, profileImage)
해결했습니다.

2022-09-07 11:38 UTC, dyjeong576 commented on teamC/dayoung/models/userDao.js
> +  });
수정했습니다.

2022-09-08 02:15 UTC, Kang-kyunghun commented
LGTM~!

2022-09-08 02:15 UTC, merged