[조준형-teamB] Assignment 1 : Project Layered pattern 적용
wecode-bootcamp-korea/37-backend-westagram pull request #67
Opened 2022-09-07 00:46 UTC by zwundzwzig

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 레이아웃 패턴 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-09-07 02:33 UTC, Kang-kyunghun requested changes

2022-09-07 02:33 UTC, Kang-kyunghun commented on teamB/junhyungcho/services/userService.js
> +const jwt = require('jsonwebtoken');
require 순서는 다음과 같이 하면 좋을 것 같습니다.
```suggestion
// 3rd-part package
const bcrypt = require('bcrypt');
const jwt = require('jsonwebtoken');

//custom package
const { userDao } = require('../models/')
```

2022-09-07 02:33 UTC, Kang-kyunghun commented on teamB/junhyungcho/services/userService.js
> +
불필요한 주석은 제거해 주세요.

2022-09-07 02:33 UTC, Kang-kyunghun commented on teamB/junhyungcho/services/userService.js
> +}
해당 유저가 작성한 게시물 목록을 가져오는 것일까요? 

그렇다면 결국 가져오는 데이터는 게시물 목록이기 때문에 user보다는 post쪽으로 분류하시면 더 좋을 것 같습니다.

2022-09-07 02:33 UTC, Kang-kyunghun commented on teamB/junhyungcho/app.js
> +    }
1. throw을 사용하면 catch로 잡은 err를 보통은 해당 함수 보다 상위에 있는 catch에서 다시 잡게 됩니다. 그래서 지금 같은 상황에서는 그냥 바로 err를 잡고 console.log로 확인하는 정도면 충분 할 것 같습니다.

```suggestion
        server.listen(PORT, () => console.log(`Server is listening on ${PORT}`));
    } catch (err) {
        console.log(err);
    } 
```

2022-09-07 02:33 UTC, Kang-kyunghun commented on teamB/junhyungcho/db/schema.sql
> +/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
schema.sql 파일이 같이 올라와 있습니다. 

구글에 github에 잘 못 올라간 파일 제거하는 방법 찾아보시고 적용해 주세요.

2022-09-07 02:33 UTC, Kang-kyunghun commented on teamB/junhyungcho/models/likeDao.js
> +    .finally(() => console.log("==========================================="));
finally를 사용하시는 이유가 따로 있을까요?

finally를 통해 의미 있는 작업을 하는 것이 아니라면 catch에서 error를 처리한 것만으로도 충분해 보입니다.

2022-09-07 02:33 UTC, Kang-kyunghun commented on teamB/junhyungcho/models/likeDao.js
> +const pushHeart = async ( userId, postId ) => {
데이터를 생성하는 것이므로 다음과 같이 이름을 수정하면 조금 더 좋을 것 같습니다.
```suggestion
const createHeart = async ( userId, postId ) => {
```

2022-09-07 02:33 UTC, Kang-kyunghun commented on teamB/junhyungcho/models/likeDao.js
> +        error.statusCode = 500;
개발자가 처리한 에러의 경우 상태코드는 4xx번대를 사용하셔야 합니다. 
500의 경우 개발자가 에러 핸들링을 안 할 경우 발생 한 에러로 보기 때문입니다.

2022-09-07 02:33 UTC, Kang-kyunghun commented on teamB/junhyungcho/models/postDao.js
> +const editPost = async ( postId, title, description, cover_image, users_id ) => {
edit이라는 용어보다 update나 modify라는 용어를 더 많이 사용합니다.

```suggestion
const updatePost = async ( postId, title, description, cover_image, users_id ) => {
```

2022-09-07 02:33 UTC, Kang-kyunghun commented on teamB/junhyungcho/models/userDao.js
> +const getAllInfo = async (userId) => {
user 정보와 해당 user가 작성한 게시글을 가져오는 역할로 보이는데, 
dao에서 이렇게 sql을 만들지 말고, 서비스에서 user정보를 가져오는 dao 한 번 호출, 특정 user가 작성한 게시물 목록 가져오는 dao한 번 호출, 총 2번의 dao를 호출하는 식으로 구성하면 더 좋을 것 같습니다.

2022-09-07 02:35 UTC, Kang-kyunghun commented
전반적으로 함수 이름을 지을 때 동사형으로 만든 것은 좋았습니다. 여기에 한 가지를 더하면 좋을 것 같은데,
1. 단순히 edit를 함수 이름 보다는 updateUser or updatePost, deleteLike 등 동사와 대상을 같이 적어주시면 좋을 것 같습니다.
2. heart의 경우 좋아요를 의미하는 것 같은데, createLike 정도가 더 알아보기 좋을 것 같습니다.

2022-09-07 04:01 UTC, zwundzwzig commented on teamB/junhyungcho/services/userService.js
> +}
유저의 정보를 가져오는데 거기에 포스트 목록을 담아 가져오는 로직을 구현하려고 해서 user쪽으로 분류했습니다! 그렇다면 변수명을 수정할까요? 아니면 그대로 post쪽으로 분류할까요?

2022-09-08 02:13 UTC, Kang-kyunghun commented
1. 코드 포멧팅이 잘 안 되고 있는 것 같습니다. VScode의 prettier라는 extension이 있습니다. 어떻게 설정하는지 찾아보고 적용해 보시면 좋을 것 같습니다.
2. 함수 이름들은 수정해 주세요.
3. conflict 해결해 주세요.

2022-09-10 15:30 UTC, closed without merging