[정윤아-teamB] Assignment 1: Error Handling
wecode-bootcamp-korea/37-backend-westagram pull request #9
Opened 2022-08-31 04:37 UTC by jeongyunah

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
express settings
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-08-31 05:42 UTC, Kang-kyunghun requested changes

2022-08-31 05:42 UTC, Kang-kyunghun commented on teamB/jeongyunah/myapp/.gitignore
> +env.js
- .env, node_modules/, db/schema.sql, .vscode 파일을 추가해주세요.
- 그 이유는 .env 파일에는 데이터베이스의 비밀번호와 같은 중요한 환경변수가 포함되어 있기 때문에, github에 올라가서는 안됩니다.
- 또한 node_modules/와 db/schma.sql, .vscode의 경우에는 개발환경에서 만들어지는 파일들입니다. 이러한 불필요한 코드는 소스코드에 포함되지 않도록 사전에 .gitignore 파일에 추가해 줍니다.

2022-08-31 05:42 UTC, Kang-kyunghun commented on teamB/jeongyunah/myapp/app.js
> +const logger = require('morgan');
- mport 순서 컨벤션에 맞게 수정해주세요! 사소한 부분이라 놓치기 쉽지만 이런 컨벤션 준수들이 모여서 좀 더 가독성 좋은 코드가 됩니다.
- 가독성을 위해서 환경변수 설정에 필요한 ‘dotenv’ 모듈을 `require('dotenv').config();`과 같이 최상단에 불러옵니다.
- 이후 라이브러리는 다음과 같은 순서로 import 해줍니다.
    - bulit-in 패키지
    - 3rd-party 패키지
    - custom 패키지
```jsx
// Example
require('dotenv').config();

// Built-in package
const http = require('http')

// 3rd-party package
const express = require('express');
const cors    = require('cors');
const app     = express();
const morgan  = require('morgan');
const { DataSource } = require('typeorm');

//custom package
 const api = require('./../api')
```

2022-08-31 05:42 UTC, Kang-kyunghun commented on teamB/jeongyunah/myapp/app.js
> +//dotenv.config();
불필요한 console.log와 주석은 제거해 주세요.

2022-08-31 05:42 UTC, Kang-kyunghun commented on teamB/jeongyunah/myapp/app.js
> +app.use(logger('combined'));
위에 3000 port로 Listen하고 있는데, 다시 여기서 3500으로 listen하고 있네요? 해당 코드는 없어도 될 것 같습니다.

2022-08-31 05:44 UTC, Kang-kyunghun commented
1. .env 파일이 안 보이는 것 같습니다. 생성 후 필요한 값들을 넣어주세요.
2. node app.js로 서버를 열고 ping을 해보셨나요?? ping까지 테스트 부탁드리겠습니다.
3. 구현사항 설명 작성시 조금 더 어떻게(HOW)에 초점을 맞춰서 작성해주세요!!
구현사항을 잘 적으면서 내가 어떻게 구현했는지 스스로 이해도를 점검해볼 수 있으며 나중에 내가 어떤 고민을 하고 문제를 어떻게 해결했는지 점검해보면서 스스로를 회고해볼 수 있는 좋은 자산이 됩니다!

2022-09-04 13:46 UTC, closed without merging

2022-09-04 13:46 UTC, jeongyunah commented
express2 브랜치로 이동 후 머지되었습니다 :)